name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "✨ Added"
    labels: [ "feature", "enhancement" ]
  - title: "🐛 Fixed"
    labels: [ "bug", "fix" ]
  - title: "🧹 Chore"
    labels: [ "chore", "infra", "ci" ]
  - title: "🧪 Tests"
    labels: [ "test" ]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
exclude-labels: [ "skip-changelog" ]
template: |
  ## Changes
  $CHANGES
