[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310']
include = '\.py$'
exclude = '''
/(
    \.git
  | __pycache__
  | \.venv
  | \.tox
)/
'''

[tool.isort]
profile = "black"
length_sort = true
force_sort_within_sections = true
line_length = 120
multi_line_output = 3
include_trailing_comma = true
