[tool.black]
line-length = 120
target-version = ['py313']

[tool.isort]
profile = "black"
line_length = 120
length_sort = true
force_sort_within_sections = true
combine_as_imports = true
known_first_party = ["tools", "logger", "tests", "app"]

[tool.ruff]
line-length = 120
target-version = "py313"
select = ["E", "F", "UP", "B", "C4", "SIM", "PL"]
ignore = ["E501", "PLR2004"]
fix = true

[tool.mypy]
python_version = "3.13"
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
no_implicit_optional = true
pretty = true
exclude = '(^\.venv|^tests/|^build|^dist)'
# [[tool.mypy.overrides]]
# module = ["tools.security", "tools.limits", "tools.system", "tools.http"]
# disallow_untyped_defs = true
