name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    name: Lint, Format Check & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt .
          pip install pytest pylint black isort

      - name: Run Black Check
        run: black --check .

      - name: Run isort Check
        run: isort --check-only .

      - name: Run Pylint
        run: pylint tools tests app.py
        continue-on-error: true

      - name: Run Tests
        run: |
          pytest -v
